
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form daftar
     */
    public daftar() {
        initComponents();
        datatable();
    }
    public void datatable(){
        DefaultTableModel tbl=new DefaultTableModel();
        try{
        Statement statement=(Statement) config.configDB().createStatement();
        ResultSet res=statement.executeQuery("SELECT pengguna.no_telp, pengguna.nama, pengguna.password, pengguna.password1, pengguna.alamat, role.id_role "
                + "FROM pengguna LEFT JOIN role  ON pengguna.id_role = role.id_role");
        while(res.next())
        {
            tbl.addRow(new Object[]{
                res.getString("no_telp"),
                res.getString("nama"),
                res.getString("password"),
                res.getString("password1"),
                res.getString("alamat"),
                res.getString("id_role")
            });
        }
    }catch (SQLException e){
            JOptionPane.showMessageDialog(null,"salah!"+e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttelepon = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        txtsandia = new javax.swing.JPasswordField();
        txtsandib = new javax.swing.JPasswordField();
        cmbposisi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttelepon.setBackground(new java.awt.Color(185, 204, 188));
        txttelepon.setBorder(null);
        getContentPane().add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 250, 20));

        txtnama.setBackground(new java.awt.Color(185, 204, 188));
        txtnama.setBorder(null);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 250, -1));

        txtalamat.setBorder(null);
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 210, -1));

        simpan.setBackground(new java.awt.Color(133, 220, 2));
        simpan.setBorder(null);
        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 80, 30));

        txtsandia.setBackground(new java.awt.Color(185, 204, 188));
        txtsandia.setBorder(null);
        getContentPane().add(txtsandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 260, -1));

        txtsandib.setBorder(null);
        getContentPane().add(txtsandib, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 260, 220, -1));

        cmbposisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Karyawan" }));
        cmbposisi.setBorder(null);
        cmbposisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbposisiActionPerformed(evt);
            }
        });
        getContentPane().add(cmbposisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 220, 30));

        jLabel1.setBackground(new java.awt.Color(185, 204, 188));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/daftar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    String no_telp = txttelepon.getText();
    String nama = txtnama.getText();
    String password = txtsandia.getText();
    String password1 = txtsandib.getText();
    String alamat = txtalamat.getText();
    String id_role = (String) cmbposisi.getSelectedItem();
    
    try{
        Statement statement = (Statement) config.configDB().createStatement();
        statement.executeUpdate("insert into pengguna(no_telp, nama, password, password1, alamat, id_role) VALUES ('"+no_telp+"','"+nama+"','"+password+"','"+password1+"','"+alamat+"','"+id_role+"')");
        statement.close();
        //JOptionPane.showMessageDialog(null, "pendaftaran berhasil!");
    }catch (Exception t){
        JOptionPane.showMessageDialog(null, "pendaftaran gagal!");
    }
    datatable();
    this.setVisible(false);
     new login().setVisible(true);
    }//GEN-LAST:event_simpanActionPerformed

    private void cmbposisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbposisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbposisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbposisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtsandia;
    private javax.swing.JPasswordField txtsandib;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
