/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS
 */
public class dasboard extends javax.swing.JFrame {

    /**
     * Creates new form dasboard
     */
    public dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JButton();
        produk = new javax.swing.JButton();
        pengguna = new javax.swing.JButton();
        penjualan = new javax.swing.JButton();
        pembelian = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(185, 204, 188));
        dashboard.setBorder(null);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 20));

        produk.setBackground(new java.awt.Color(185, 204, 188));
        produk.setBorder(null);
        produk.setContentAreaFilled(false);
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        pengguna.setBackground(new java.awt.Color(185, 204, 188));
        pengguna.setBorder(null);
        pengguna.setContentAreaFilled(false);
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 30));

        penjualan.setBackground(new java.awt.Color(185, 204, 188));
        penjualan.setBorder(null);
        penjualan.setContentAreaFilled(false);
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        pembelian.setBackground(new java.awt.Color(185, 204, 188));
        pembelian.setBorder(null);
        pembelian.setContentAreaFilled(false);
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        laporan.setBackground(new java.awt.Color(185, 204, 188));
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, 30));

        keluar.setBorder(null);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 12, 90, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dasboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
    this.setVisible(false);
     new dasboard().setVisible(true);
    }//GEN-LAST:event_dashboardActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
    this.setVisible(false);
     new produk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
    this.setVisible(false);
     new penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
    this.setVisible(false);
     new pembelian().setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
    this.setVisible(false);
     new pengguna().setVisible(true);
    }//GEN-LAST:event_penggunaActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
    this.setVisible(false);
     new laporan().setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
    dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JButton pembelian;
    private javax.swing.JButton pengguna;
    private javax.swing.JButton penjualan;
    private javax.swing.JButton produk;
    // End of variables declaration//GEN-END:variables
}
