
import java.sql.Connection;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.joni.Config;
import java.sql.Statement;
import javax.swing.JRootPane;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.config;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        daftar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtpassword.setBorder(null);
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 160, 30));

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtusername.setForeground(new java.awt.Color(51, 51, 51));
        txtusername.setBorder(null);
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 150, 30));

        login.setBackground(new java.awt.Color(133, 220, 2));
        login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                loginAncestorRemoved(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 100, 30));

        daftar.setBorder(null);
        daftar.setContentAreaFilled(false);
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 610, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

try {
    String sql = "SELECT no_telp, password FROM pengguna WHERE no_telp=? AND password=? GROUP BY no_telp";
    java.sql.Connection conn = (Connection) config.configDB();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, txtusername.getText());
    pst.setString(2, txtpassword.getText());
    java.sql.ResultSet rs = pst.executeQuery();
    
    if (rs.next()) {
        //JOptionPane.showMessageDialog(null, "Berhasil login");
        this.setVisible(false);
        new dasboard().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Username atau password salah");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_loginActionPerformed

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
     this.setVisible(false);
     new daftar().setVisible(true);
    }//GEN-LAST:event_daftarActionPerformed

    private void loginAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_loginAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
  
}
