/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException; 
import javax.swing.JOptionPane;
import koneksi.config;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WINDOWS
 */
public class pembelian extends javax.swing.JFrame {

    /**
     * Creates new form pembelian
     */
    public pembelian() {
        initComponents();
        datatable();
    }
public void datatable(){
    DefaultTableModel tbl=new DefaultTableModel();
    tbl.addColumn("Id Pembelian");
    tbl.addColumn("Tgl Pembelian");
    tbl.addColumn("Jenis Pembelian");
    tbl.addColumn("Tagihan");
    tbl.addColumn("Keterangan");
    table.setModel(tbl);
    try{
        Statement statement=(Statement) config.configDB().createStatement();
        ResultSet res=statement.executeQuery("SELECT b.id_pembelian, b.tgl_pembelian, b.jenis_pembelian, b.tagihan, b.keterangan "
                + "FROM pembelian b LEFT JOIN jenis_beli g ON b.id_pembelian = g.id_beli");
        while(res.next())
        {
            tbl.addRow(new Object[]{
                res.getString("id_pembelian"),
                res.getString("tgl_pembelian"),
                res.getString("jenis_pembelian"),
                res.getString("tagihan"),
                res.getString("keterangan")
            });
            table.setModel(tbl);
        }
    }catch (Exception e){
            JOptionPane.showMessageDialog(null,"salah!"+e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttagihan = new javax.swing.JTextField();
        txtketerangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        keluar = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        produk = new javax.swing.JButton();
        penjualan = new javax.swing.JButton();
        pembelian = new javax.swing.JButton();
        pengguna = new javax.swing.JButton();
        cmbcari = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        cmbjenis = new javax.swing.JComboBox<>();
        edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txttagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 200, -1));
        getContentPane().add(txtketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 200, -1));

        table.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 940, 350));

        keluar.setBorder(null);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 12, 90, 60));

        hapus.setBorder(null);
        hapus.setContentAreaFilled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 100, 30));

        tambah.setBorder(null);
        tambah.setContentAreaFilled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 100, 30));

        dashboard.setBackground(new java.awt.Color(185, 204, 188));
        dashboard.setBorder(null);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 20));

        produk.setBackground(new java.awt.Color(185, 204, 188));
        produk.setBorder(null);
        produk.setContentAreaFilled(false);
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        penjualan.setBackground(new java.awt.Color(185, 204, 188));
        penjualan.setBorder(null);
        penjualan.setContentAreaFilled(false);
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        pembelian.setBackground(new java.awt.Color(185, 204, 188));
        pembelian.setBorder(null);
        pembelian.setContentAreaFilled(false);
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        pengguna.setBackground(new java.awt.Color(185, 204, 188));
        pengguna.setBorder(null);
        pengguna.setContentAreaFilled(false);
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 30));

        cmbcari.setBackground(new java.awt.Color(0, 204, 0));
        cmbcari.setBorder(null);
        cmbcari.setContentAreaFilled(false);
        cmbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcariActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 270, 20, 30));

        laporan.setBackground(new java.awt.Color(185, 204, 188));
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, 30));

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcari.setBorder(null);
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 275, 140, 20));

        cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operasional", "Lain-Lain" }));
        getContentPane().add(cmbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 200, -1));

        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        this.setVisible(false);
        new dasboard().setVisible(true);
    }//GEN-LAST:event_dashboardActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        this.setVisible(false);
        new produk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        this.setVisible(false);
        new penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        this.setVisible(false);
        new pembelian().setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
        this.setVisible(false);
        new pengguna().setVisible(true);
    }//GEN-LAST:event_penggunaActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
    String jenis_pembelian = (String) cmbjenis.getSelectedItem();
    String tagihan = txttagihan.getText();
    String keterangan = txtketerangan.getText();
    try{
        Statement statement = (Statement) config.configDB().createStatement();
        statement.executeUpdate("insert into pembelian(jenis_pembelian, tagihan, keterangan) VALUES ('"+jenis_pembelian+"','"+tagihan+"','"+keterangan+"')");
        statement.close();
        JOptionPane.showMessageDialog(null, "data berhasil ditambah!");
    }catch (Exception t){
    t.printStackTrace();
    JOptionPane.showMessageDialog(null, "data gagal ditambah!");
    }
    datatable();
 
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    String id_pembelian = txttagihan.getText();
    try{
        Statement statement = (Statement) config.configDB().createStatement();
        statement.executeUpdate("DELETE from pembelian where id_pembelian=('"+id_pembelian+"');");
        JOptionPane.showMessageDialog(null,"data berhasil di HAPUS!");
        txttagihan.setText("");
        txtketerangan.setText("");
        txttagihan.requestFocus();
    }catch (Exception t){
        JOptionPane.showMessageDialog(null,"Data gagal di HAPUS!");
    }
    datatable();
    }//GEN-LAST:event_hapusActionPerformed

    private void cmbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcariActionPerformed
        try {
            java.sql.Connection conn=(java.sql.Connection)koneksi.config.configDB();
            String sql = "Select * from pembelian where id_pembelian='"+txtcari.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next())
            cmbjenis.setSelectedItem(rs.getString(5));
            txttagihan.setText(rs.getString(4));
            txtketerangan.setText(rs.getString(3));
            
            JOptionPane.showMessageDialog(null,"Data Pembelian Dengan Id '"+txtcari.getText()+"' Ditemukan");
        } catch (Exception t){
            JOptionPane.showMessageDialog(null,"Data Pembelian Dengan Id '"+txtcari.getText()+"' Tidak Ditemukan");
        }
        datatable();
    }//GEN-LAST:event_cmbcariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            java.sql.Connection conn = (java.sql.Connection) koneksi.config.configDB();
//            String sql = "UPDATE pembelian SET jenis_pembelian=?, tagihan=?, keterangan=? WHERE id_pembelian=?";
            String sql = "UPDATE pembelian SET jenis_pembelian=?, tagihan=?, keterangan=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, (String) cmbjenis.getSelectedItem());
            pst.setString(2, txttagihan.getText());
            pst.setString(3, txtketerangan.getText());           
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di edit");
            e.printStackTrace();
        }
        datatable();
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbcari;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JButton pembelian;
    private javax.swing.JButton pengguna;
    private javax.swing.JButton penjualan;
    private javax.swing.JButton produk;
    private javax.swing.JTable table;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txttagihan;
    // End of variables declaration//GEN-END:variables
}
