
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS
 */
public class pengguna extends javax.swing.JFrame {

    /**
     * Creates new form pengguna
     */
    public pengguna() {
        initComponents();
        datatable();
    }
public void datatable(){
    DefaultTableModel tbl=new DefaultTableModel();
    //tbl.addColumn("Id");
    tbl.addColumn("Nama");
    tbl.addColumn("Alamat");
    tbl.addColumn("No Telpon");
    tbl.addColumn("Role");
    table.setModel(tbl);
    try{
        Statement statement=(Statement) config.configDB().createStatement();
        ResultSet res=statement.executeQuery("SELECT u.nama, u.alamat, u.no_telp, u.id_role FROM pengguna u LEFT JOIN role r ON u.id_role = r.id_role");
        while(res.next())
        {
            tbl.addRow(new Object[]{
                //res.getString("id"),
                res.getString("nama"),
                res.getString("alamat"),
                res.getString("no_telp"),
                res.getString("id_role")
            });
            table.setModel(tbl);
        }
    }catch (Exception e){
            JOptionPane.showMessageDialog(null,"salah!"+e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cmbrole = new javax.swing.JComboBox<>();
        keluar = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        produk = new javax.swing.JButton();
        penjualan = new javax.swing.JButton();
        pengguna = new javax.swing.JButton();
        pembelian = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        cmbcari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 200, -1));

        txtalamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 200, -1));

        txtnotelp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 200, -1));

        table.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 940, 320));

        cmbrole.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Karyawan" }));
        getContentPane().add(cmbrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 200, -1));

        keluar.setBorder(null);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 12, 90, 60));

        hapus.setBorder(null);
        hapus.setContentAreaFilled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 280, 100, 30));

        dashboard.setBackground(new java.awt.Color(185, 204, 188));
        dashboard.setBorder(null);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 20));

        produk.setBackground(new java.awt.Color(185, 204, 188));
        produk.setBorder(null);
        produk.setContentAreaFilled(false);
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        penjualan.setBackground(new java.awt.Color(185, 204, 188));
        penjualan.setBorder(null);
        penjualan.setContentAreaFilled(false);
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        pengguna.setBackground(new java.awt.Color(185, 204, 188));
        pengguna.setBorder(null);
        pengguna.setContentAreaFilled(false);
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 30));

        pembelian.setBackground(new java.awt.Color(185, 204, 188));
        pembelian.setBorder(null);
        pembelian.setContentAreaFilled(false);
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        laporan.setBackground(new java.awt.Color(185, 204, 188));
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, 30));

        cmbcari.setBackground(new java.awt.Color(0, 204, 0));
        cmbcari.setBorder(null);
        cmbcari.setContentAreaFilled(false);
        cmbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcariActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 340, 20, 30));

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcari.setBorder(null);
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 340, 150, 20));

        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengguna (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        this.setVisible(false);
        new dasboard().setVisible(true);
    }//GEN-LAST:event_dashboardActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        this.setVisible(false);
        new produk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        this.setVisible(false);
        new penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        this.setVisible(false);
        new pembelian().setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
        this.setVisible(false);
        new pengguna().setVisible(true);
    }//GEN-LAST:event_penggunaActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    String cari = txtcari.getText();
    try{
        Statement statement = (Statement) config.configDB().createStatement();
        statement.executeUpdate("DELETE from pengguna where nama=('"+cari+"');");
        JOptionPane.showMessageDialog(null,"data berhasil di HAPUS!");
        txtnama.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txtnotelp.setText("");
        txtnama.requestFocus();
    }catch (Exception t){
        JOptionPane.showMessageDialog(null,"Data gagal di HAPUS!");
    }
    datatable();
    }//GEN-LAST:event_hapusActionPerformed

    private void cmbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcariActionPerformed
        try {
            java.sql.Connection conn=(java.sql.Connection)koneksi.config.configDB();
            String sql = "Select * from pengguna where nama='"+txtcari.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next())
            //txtid.setText(rs.getString(1));
            txtnama.setText(rs.getString(3));
            txtalamat.setText(rs.getString(4));
            txtnotelp.setText(rs.getString(5));
            cmbrole.setSelectedItem(rs.getString(6));
            JOptionPane.showMessageDialog(null,"Data Pengguna Dengan nama '"+txtcari.getText()+"' Ditemukan");
        } catch (Exception t){
            JOptionPane.showMessageDialog(null,"Data Pengguna Dengan nama '"+txtcari.getText()+"' Tidak Ditemukan");
        }
        datatable();
    }//GEN-LAST:event_cmbcariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    try {
    java.sql.Connection conn = (java.sql.Connection) koneksi.config.configDB();
    String sql = "UPDATE pengguna SET nama=?, alamat=?, id_role=? WHERE no_telp=?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, txtnama.getText());
    pst.setString(2, txtalamat.getText());
    pst.setString(3, (String) cmbrole.getSelectedItem());
    pst.setString(4, txtnotelp.getText());
    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data berhasil di edit");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data Gagal di edit");
        e.printStackTrace();
    }
    datatable();
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbcari;
    private javax.swing.JComboBox<String> cmbrole;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JButton pembelian;
    private javax.swing.JButton pengguna;
    private javax.swing.JButton penjualan;
    private javax.swing.JButton produk;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotelp;
    // End of variables declaration//GEN-END:variables
}
