
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.config;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author WINDOWS
 */
import javax.swing.JComboBox;
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form penjualan
     * 
     */
    public penjualan() {
        initComponents();
        datatable();
    }
    //Connection con = koneksi.config.configDB();

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();

        tbl.addColumn("Id");
        tbl.addColumn("Tanggal Penjualan");
        tbl.addColumn("Nama Produk");
        tbl.addColumn("Harga");
        tbl.addColumn("Jumlah Terjual");
        tbl.addColumn("Tagihan");

        try {
            Statement statement = config.configDB().createStatement();
            ResultSet res = statement.executeQuery("SELECT j.id_penjualan, j.tgl_penjualan, p.nama_produk, p.harga_produk, j.jumlah_beli, (p.harga_produk * j.jumlah_beli) AS tagihan "
                    + "FROM penjualan j LEFT JOIN produk p ON j.nama_produk = p.nama_produk");

            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getInt("id_penjualan"),
                    res.getString("tgl_penjualan"),
                    res.getString("nama_produk"),
                    res.getInt("harga_produk"),
                    res.getInt("jumlah_beli"),
                    res.getInt("tagihan")
                });
            }

            table.setModel(tbl);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }}
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtjumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        keluar = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        produk = new javax.swing.JButton();
        penjualan = new javax.swing.JButton();
        pembelian = new javax.swing.JButton();
        pengguna = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        cmbcari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtid2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 200, -1));

        table.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 930, 440));

        keluar.setBorder(null);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 12, 90, 60));

        hapus.setBorder(null);
        hapus.setContentAreaFilled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, 100, 30));

        tambah.setBorder(null);
        tambah.setContentAreaFilled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 100, 30));

        dashboard.setBackground(new java.awt.Color(185, 204, 188));
        dashboard.setBorder(null);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 20));

        produk.setBackground(new java.awt.Color(185, 204, 188));
        produk.setBorder(null);
        produk.setContentAreaFilled(false);
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        penjualan.setBackground(new java.awt.Color(185, 204, 188));
        penjualan.setBorder(null);
        penjualan.setContentAreaFilled(false);
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        pembelian.setBackground(new java.awt.Color(185, 204, 188));
        pembelian.setBorder(null);
        pembelian.setContentAreaFilled(false);
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        pengguna.setBackground(new java.awt.Color(185, 204, 188));
        pengguna.setBorder(null);
        pengguna.setContentAreaFilled(false);
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 30));

        laporan.setBackground(new java.awt.Color(185, 204, 188));
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, 30));

        cmbcari.setBackground(new java.awt.Color(0, 204, 0));
        cmbcari.setBorder(null);
        cmbcari.setContentAreaFilled(false);
        cmbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcariActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 220, 20, 20));

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcari.setBorder(null);
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 220, 140, 20));

        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 110, 30));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 200, -1));

        txtid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 90, -1));

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/penjualan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        this.setVisible(false);
        new dasboard().setVisible(true);
    }//GEN-LAST:event_dashboardActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        this.setVisible(false);
        new produk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        this.setVisible(false);
        new penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        this.setVisible(false);
        new pembelian().setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
        this.setVisible(false);
        new pengguna().setVisible(true);
    }//GEN-LAST:event_penggunaActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed
        
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String nama_produk = txtid.getText();
        String jumlah_beli = txtjumlah.getText();
        try {
            Statement statement = (Statement) config.configDB().createStatement();
            statement.executeUpdate("insert into penjualan(nama_produk, jumlah_beli) VALUES('" + nama_produk + "','" + jumlah_beli + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil ditambah!");
        }catch (Exception t){
            t.printStackTrace();
            JOptionPane.showMessageDialog(null, "data gagal ditambah!");
            }
        datatable();
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String id_penjualan = txtid2.getText();
        try {
            Statement statement = (Statement) config.configDB().createStatement();
            statement.executeUpdate("DELETE from penjualan where id_penjualan=('" + id_penjualan + "');");
            JOptionPane.showMessageDialog(null, "data berhasil di HAPUS!");
            txtid.setText("");
            txtid2.setText("");
            txtjumlah.setText("");
            txtid.requestFocus();
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal di HAPUS!");
        }
        datatable();
    }//GEN-LAST:event_hapusActionPerformed

    private void cmbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcariActionPerformed
        try {
            java.sql.Connection conn = (java.sql.Connection) koneksi.config.configDB();
//            String sql = "Select * from penjualan where id_produk='" + txtcari.getText() + "'or jumlah_beli='" + txtcari.getText() + "'";
            String sql = "Select * from penjualan where id_penjualan='"+txtcari.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                //txtid.setSelectedItem(rs.getString(1));
//                String id_pembelian = txtid.getText();
                txtid.setText(rs.getString(2));
                txtid2.setText(rs.getString(1));
                txtjumlah.setText(rs.getString(4));
            }
//            txtjumlah.(String) txtid.getSelectedItem();
            JOptionPane.showMessageDialog(null, "Data Produk Dengan Id '" + txtcari.getText() + "' Ditemukan");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data Produk Dengan Id '" + txtcari.getText() + "' Tidak Ditemukan");
        }
        datatable();
    }//GEN-LAST:event_cmbcariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {          
            java.sql.Connection conn = (java.sql.Connection) koneksi.config.configDB();
            String sql = "UPDATE penjualan SET jumlah_beli=?,nama_produk=? WHERE id_penjualan=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);   
            pst.setInt(1,Integer.parseInt(txtjumlah.getText()));
            pst.setString(2,txtid.getText());  
            pst.setString(3,txtid2.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di edit");
            e.printStackTrace();
        }
        datatable();
    }//GEN-LAST:event_editActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbcari;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JButton pembelian;
    private javax.swing.JButton pengguna;
    private javax.swing.JButton penjualan;
    private javax.swing.JButton produk;
    private javax.swing.JTable table;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid2;
    private javax.swing.JTextField txtjumlah;
    // End of variables declaration//GEN-END:variables

}

