/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException; 
import javax.swing.JOptionPane;
import koneksi.config;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WINDOWS
 */
public class produk extends javax.swing.JFrame {

    /**
     * Creates new form produk
     */
    public produk() {
        initComponents();
        datatable();
    }
public void datatable(){
    DefaultTableModel tbl=new DefaultTableModel();
    tbl.addColumn("Id");
    tbl.addColumn("Nama Produk");
    tbl.addColumn("Kategori");
    tbl.addColumn("Jumlah Stok");
    tbl.addColumn("Harga Satuan"); 
    table.setModel(tbl);
    try{
        Statement statement=(Statement) config.configDB().createStatement();
        ResultSet res=statement.executeQuery("SELECT p.id_produk, p.nama_produk, k.nama_kategori, p.jumlah_stok, p.harga_produk "
                + "FROM produk p LEFT JOIN kategori_produk k ON p.nama_kategori = k.nama_kategori");
        while(res.next())
        {
            tbl.addRow(new Object[]{
                res.getString("id_produk"),
                res.getString("nama_produk"),
                res.getString("nama_kategori"),
                res.getString("jumlah_stok"),
                res.getString("harga_produk")
            });
            table.setModel(tbl);
        }
    }catch (Exception e){
            JOptionPane.showMessageDialog(null,"salah!"+e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtid = new javax.swing.JTextField();
        txtnamaproduk = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        txthargasatuan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        dashboard = new javax.swing.JButton();
        produk = new javax.swing.JButton();
        pembelian = new javax.swing.JButton();
        pengguna = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        penjualan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbkategori = new javax.swing.JComboBox<>();
        edit = new javax.swing.JButton();
        cmbcari = new javax.swing.JButton();
        txtjumlahstok = new javax.swing.JTextField();
        gambar = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 200, -1));
        getContentPane().add(txtnamaproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 200, -1));

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcari.setBorder(null);
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 150, -1));

        txthargasatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargasatuanActionPerformed(evt);
            }
        });
        getContentPane().add(txthargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 200, -1));

        table.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 940, 350));

        dashboard.setBackground(new java.awt.Color(185, 204, 188));
        dashboard.setBorder(null);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 20));

        produk.setBackground(new java.awt.Color(185, 204, 188));
        produk.setBorder(null);
        produk.setContentAreaFilled(false);
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        pembelian.setBackground(new java.awt.Color(185, 204, 188));
        pembelian.setBorder(null);
        pembelian.setContentAreaFilled(false);
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        pengguna.setBackground(new java.awt.Color(185, 204, 188));
        pengguna.setBorder(null);
        pengguna.setContentAreaFilled(false);
        pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 30));

        laporan.setBackground(new java.awt.Color(185, 204, 188));
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, 30));

        penjualan.setBackground(new java.awt.Color(185, 204, 188));
        penjualan.setBorder(null);
        penjualan.setContentAreaFilled(false);
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        keluar.setBorder(null);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 12, 90, 60));

        tambah.setBorder(null);
        tambah.setContentAreaFilled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 100, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 100, 30));

        cmbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        cmbkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkategoriActionPerformed(evt);
            }
        });
        getContentPane().add(cmbkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 200, -1));

        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 240, 110, 30));

        cmbcari.setBackground(new java.awt.Color(0, 204, 0));
        cmbcari.setBorder(null);
        cmbcari.setContentAreaFilled(false);
        cmbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcariActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 310, 20, 30));

        txtjumlahstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahstokActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlahstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 200, -1));

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produk.png"))); // NOI18N
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        this.setVisible(false);
        new dasboard().setVisible(true);
    }//GEN-LAST:event_dashboardActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        this.setVisible(false);
        new produk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        this.setVisible(false);
        new penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        this.setVisible(false);
        new pembelian().setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penggunaActionPerformed
        this.setVisible(false);
        new pengguna().setVisible(true);
    }//GEN-LAST:event_penggunaActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
    String id_produk = txtid.getText();
    String nama_produk = txtnamaproduk.getText();
    String harga_produk = txthargasatuan.getText();
    String nama_kategori = (String) cmbkategori.getSelectedItem();
    String jumlah_stok = txtjumlahstok.getText();
    try{
        Statement statement = (Statement) config.configDB().createStatement();
        statement.executeUpdate("insert into produk(id_produk, nama_produk, harga_produk, nama_kategori, jumlah_stok) VALUES ('"+id_produk+"','"+nama_produk+"','"+harga_produk+"','"+nama_kategori+"','"+jumlah_stok+"')");
        statement.close();
        JOptionPane.showMessageDialog(null, "data berhasil ditambah!");
    }catch (Exception t){
         t.printStackTrace();
        JOptionPane.showMessageDialog(null, "data gagal ditambah!");
    }
    datatable();
 
    }//GEN-LAST:event_tambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String id_produk = txtid.getText();
    try{
        Statement statement = (Statement) config.configDB().createStatement();
//        JOptionPane.showConfirmDialog(null,"Apakah mau dihapus?","Hapus",JOptionPane.YES_NO_OPTION);
        statement.executeUpdate("DELETE from produk where id_produk=('"+id_produk+"');");
        JOptionPane.showMessageDialog(null,"data berhasil di HAPUS!");
        txtid.setText("");
        txtnamaproduk.setText("");
        txthargasatuan.setText("");
        txtjumlahstok.setText("");
        txtcari.setText("");
        txtid.requestFocus();
    }catch (Exception t){
        JOptionPane.showMessageDialog(null,"Data gagal di HAPUS!");
    }
    datatable();
    }//GEN-LAST:event_jButton1ActionPerformed
 
    
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    try {
    java.sql.Connection conn = (java.sql.Connection) koneksi.config.configDB();
    String sql = "UPDATE produk SET nama_produk=?, jumlah_stok=?, harga_produk=?, nama_kategori=? WHERE id_produk=?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, txtnamaproduk.getText());
    pst.setInt(2, Integer.parseInt(txtjumlahstok.getText()));
    pst.setInt(3, Integer.parseInt(txthargasatuan.getText()));
    pst.setString(4, (String) cmbkategori.getSelectedItem());
    pst.setInt(5, Integer.parseInt(txtid.getText()));
    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data berhasil di edit");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data Gagal di edit");
        e.printStackTrace();
    }
    datatable();

    }//GEN-LAST:event_editActionPerformed

    private void cmbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcariActionPerformed
    try {
        java.sql.Connection conn=(java.sql.Connection)koneksi.config.configDB();
        String sql = "Select * from produk where nama_produk='"+txtcari.getText()+"'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery(sql);
        if (rs.next()){
           txtid.setText(rs.getString(1));
           txtnamaproduk.setText(rs.getString(2));
           txtjumlahstok.setText(rs.getString(4));
           txthargasatuan.setText(rs.getString(5));
           cmbkategori.setSelectedItem(rs.getString(3));
        }
        
           JOptionPane.showMessageDialog(null,"Data Produk Dengan Id '"+txtcari.getText()+"' Ditemukan");
    } catch (Exception t){
    JOptionPane.showMessageDialog(null,"Data Produk Dengan Id '"+txtcari.getText()+"' Tidak Ditemukan");
    }
    datatable();
    }//GEN-LAST:event_cmbcariActionPerformed

    private void txtjumlahstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahstokActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txthargasatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargasatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargasatuanActionPerformed

    private void cmbkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbcari;
    private javax.swing.JComboBox<String> cmbkategori;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton edit;
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton laporan;
    private javax.swing.JButton pembelian;
    private javax.swing.JButton pengguna;
    private javax.swing.JButton penjualan;
    private javax.swing.JButton produk;
    private javax.swing.JTable table;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthargasatuan;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjumlahstok;
    private javax.swing.JTextField txtnamaproduk;
    // End of variables declaration//GEN-END:variables
}
